<a href="https://colab.research.google.com/github/cmorris2945/CNN_TELOMERES/blob/master/Chapter_6_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.digitalvidya.com/wp-content/uploads/2013/05/Digital-Vidya-Website-Logo-HD-2-300x95.png">

This assignment is almost like a small project. By now you have accumulated sufficient skills to be able to solve problems that a Python developer would do in their work. 
<br> It is very often when we are required to analyse a trace log of a given software or troubleshooting or regular maintenance. 
<br> In this project we will take one such example of a HTTP log. Apache HTTP web server is one of the most popular web servers and it logs all traffic information to a file called "access" log. 

**What is HTTP access log?**
<br> One of the many pieces of the Website puzzle is Web logs. Traffic analysis is central to most Websites, and the key to getting the most out of your traffic analysis revolves around how you configure your Web logs. Apache is one of the most, if not the most powerful open source solutions for Website operations. You will find that Apache’s Web logging features are flexible for the single Website or for managing numerous domains requiring Web log analysis.
<br> Following is an example of the information that is written to a access log file.
dialup02.aloha.com - - [01/Jun/1995:00:57:12 -0600] "GET /~lowey/encyclopedia/help.html" 200 2570

1. Host making the request. Hosts are identified as either local or remote.

2. Timestamp in the format "DAY MON DD HH:MM:SS YYYY", where DAY is the day of the week, MON is the name of the month, DD is the day of the month, HH:MM:SS is the time of day using a 24-hour clock, and YYYY is the year. The timezone is -0700 between 30/Oct/1994:01:30:57 and 02/Apr/1995:03:03:26. For all other requests, the timezone is -0600.

3. HTTP method GET/POST followed by the url. 

4. HTTP reply code.

5. Bytes in the reply.

## Objective of the project : 
<br> To understand how the company's website is performing
    <br>a) What are the different webpages coming in?
    <br>b) What is the frequency of hits?
    <br>c) What is the time interval in which the most accessed url being hit?
    
<font color=orange>### IMPORTANT NOTE </font>
<br> Typically, access log files have millions of rows for the practice purpose we have trimmed it down to a few lines.

## How to achieve these objectives as a programmer?
You are encouraged to do your own designing for this problem. Once you have identified the different functions, you can then  refer against this particular solution.
You may do an exercise of checking the elegancy of the solution.

## Thinking functions
> Opening a file, reading it and displaying its contents
> <br>Conversion from datetime to string and vice versa
> <br>Using regular expressions to extract relevant text out of whole text
> <br>Writing to a file
> <br>Of course, creating functions


**Q. Create a function to display first n lines of a file**

In [6]:
def show_contents(file_name, no_of_lines): 
    '''
    Open the file and use read() method to show the contents of the file
    Show only n number of lines.
    Use try-except
    '''
    # Start Code Here
    try:
      with open(file_name) as f:
         
        for index, line in enumerate(f):
        
          # This statement below will never be true, because for "number of lines == 0"  -->> if index == no_of_lines-1: If you us this in the if statement
          if index < no_of_lines:
          
            print(line)
          else:
            break
        #if index < no_of_lines:
          #raise UserWarning("You requested more lies tha you requested i the actual file")
    except FileNotFoundError:
      print("I need a file to run through...") 
    # End Code Here

In [7]:
show_contents("usask_access_log.txt", 5)

dialup02.aloha.com - - [01/Jun/1995:00:57:12 -0600] "GET /~lowey/encyclopedia/help.html" 200 2570

dialup02.aloha.com - - [01/Jun/1995:00:58:23 -0600] "GET /~lowey/encyclopedia/volume_index.html" 200 7445

fire.server.net - - [01/Jun/1995:00:59:21 -0600] "GET /~scottp/free.html" 200 5759

fire.server.net - - [01/Jun/1995:00:59:22 -0600] "GET /~scottp/fn1.gif" 200 2164

dialup02.aloha.com - - [01/Jun/1995:00:59:40 -0600] "GET /~lowey/encyclopedia/m/index.html" 200 1898



<table>
  <tr style = "align : left">
  <td>**Expected Output:**<td>
    <td style="text-align:left">dialup02.aloha.com - - [01/Jun/1995:00:57:12 -0600] "GET /~lowey/encyclopedia/help.html" 200 2570

<br>dialup02.aloha.com - - [01/Jun/1995:00:58:23 -0600] "GET /~lowey/encyclopedia/volume_index.html" 200 7445

<br>fire.server.net - - [01/Jun/1995:00:59:21 -0600] "GET /~scottp/free.html" 200 5759

<br>fire.server.net - - [01/Jun/1995:00:59:22 -0600] "GET /~scottp/fn1.gif" 200 2164

<br>dialup02.aloha.com - - [01/Jun/1995:00:59:40 -0600] "GET /~lowey/encyclopedia/m/index.html" 200 1898</td>
  </tr>
</table>
    

**Q. Print total number of unique urls**

In this question you need to use regular expression.

In case you have not come accross regular expression:

We have used re.search method. (https://docs.python.org/3.6/library/re.html#re.search)

We have already implemented the solution for this question.

In [8]:
import re

def get_urls(file_name):
    '''
        Create a set of unique urls using regex
        Returns:
            unique_urls : list of unique urls
            all_urls : list of all urls
    '''
    unique_urls = set()
    all_urls = []
    
    with open(file_name) as f:
        
        for line in f:
            searchObj = re.search( r'([""])[^\1]*\1', line)    

            if searchObj:
                s = searchObj.group()
                if s.startswith('"'):                   # removing starting double quotes
                    s = s[1:] 
    
                if s.endswith('"'):                      # removing ending double quotes
                    s = s[:-1]
                    
                unique_urls.add(s)
                all_urls.append(s)
            else:
                pass 
    
    return unique_urls,all_urls

In [9]:
unique_urls,all_urls = get_urls("usask_access_log.txt")

In [10]:
len(unique_urls)

133

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>133</td>
  </tr>
</table>  

In [11]:
len(all_urls)

217

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>217</td>
  </tr>
</table>  

** Q Find the first five  most frequent urls.**

Note : Use Counter from collections module.

https://docs.python.org/3.6/library/collections.html#collections.Counter


In [12]:
from collections import Counter

def frequency(urls):
    '''
        Using Counter create a dictionary with key as url and the corresponding frequency as value
    '''
    # Start Code Here
    c = Counter(urls).most_common()
    return c

    # End Code Here

In [13]:
frequency(all_urls)[:5]

[('GET /~scottp/free.html', 15),
 ('GET /~scottp/publish.html', 7),
 ('GET /~macphed/finite/fe_resources/fe_resources.html', 7),
 ('GET /~scottp/fn1.gif', 5),
 ('GET /~macphed/finite/fe_resources/node1.html', 4)]



**Q Parse the timestamp and create a list of dictionaries containing the date, hour, minutes, seconds of each row in the file.**

In [14]:
import re 
from datetime import date, time, datetime, timedelta
def parse_timestamp(file_name):
    with open(file_name) as f:
        '''
        This function takes file name as input and returns two lists 
            1. timestamp_list - List containing all timestamps eg. 01/Jun/1995:00:59:53
            2. timestamp - List containing all timestamps in the form of dictionaries containing the date, hour, minutes, seconds of each row in the file
        
        '''
        # Start Code Here
        timestamp_list = []
        timestamp = []
        
        for line in f:
            searchObj = re.search( r'\[.*\]', line)
            if searchObj:
              s = searchObj.group()
              s = s[1:-1]
              s = s.split()[0]
              timestamp_list.append(s)
              dt = datetime.strptime(s, '%d/%b/%Y:%H:%M:%S')
              time_stamp_dict = {}
              time_stamp_dict["date"] = dt.strftime('%d/%b/%Y')
              time_stamp_dict["hour"] = dt.strftime('%H')
              time_stamp_dict["minutes"] = dt.strftime('%M')
              time_stamp_dict["seconds"] = dt.strftime('%S')
              timestamp.append(time_stamp_dict) 


        # End Code Here
                
    return timestamp_list, timestamp

In [15]:
timestamp_list, timestamp = parse_timestamp("usask_access_log.txt")

In [16]:
# first 5

timestamp_list[:5]

['01/Jun/1995:00:57:12',
 '01/Jun/1995:00:58:23',
 '01/Jun/1995:00:59:21',
 '01/Jun/1995:00:59:22',
 '01/Jun/1995:00:59:40']

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>['01/Jun/1995:00:57:12',
 <br>'01/Jun/1995:00:58:23',
 <br>'01/Jun/1995:00:59:21',
 <br>'01/Jun/1995:00:59:22',
 <br>'01/Jun/1995:00:59:40']</td>
  </tr>
</table>

In [17]:
# first 5

timestamp[:5]

[{'date': '01/Jun/1995', 'hour': '00', 'minutes': '57', 'seconds': '12'},
 {'date': '01/Jun/1995', 'hour': '00', 'minutes': '58', 'seconds': '23'},
 {'date': '01/Jun/1995', 'hour': '00', 'minutes': '59', 'seconds': '21'},
 {'date': '01/Jun/1995', 'hour': '00', 'minutes': '59', 'seconds': '22'},
 {'date': '01/Jun/1995', 'hour': '00', 'minutes': '59', 'seconds': '40'}]

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>[{'date': '01/Jun/1995', 'hours': '00', 'minutes': '57', 'seconds': '12'},
 <br>{'date': '01/Jun/1995', 'hours': '00', 'minutes': '58', 'seconds': '23'},
 <br>{'date': '01/Jun/1995', 'hours': '00', 'minutes': '59', 'seconds': '21'},
 <br>{'date': '01/Jun/1995', 'hours': '00', 'minutes': '59', 'seconds': '22'},
 <br>{'date': '01/Jun/1995', 'hours': '00', 'minutes': '59', 'seconds': '40'}]</td>
  </tr>
</table>
    

**Q. In all the timestamps replace month name with month number and convert all the strings to datetime store them in a new list called as timestamp_datetime_list**

In [21]:
from datetime import date,time,datetime,timedelta

In [25]:
def string_to_date(string_date):
    '''
        Convert string to date using strptime() method
    '''
    # Start Code Here

    return datetime.strptime(string_date, '%d/%b/%Y:%H:%M:%S')


   # 01/Jun/1995:00:57:12
    # End Code Here

In [28]:
print(string_to_date(timestamp_list[0]))

1995-06-01 00:57:12


In [29]:
def replace_month(string):
    
    # Start Code Here
    dt = string_to_date(string)
    return dt.strftime('%d/%m/%Y:%H:%M:%S')

    # End Code Here

In [32]:
# Start Code Here

timestamp_datetime_list = [string_to_date(ts) for ts in timestamp_list]



# End Code Here

In [33]:
timestamp_datetime_list[:5]

[datetime.datetime(1995, 6, 1, 0, 57, 12),
 datetime.datetime(1995, 6, 1, 0, 58, 23),
 datetime.datetime(1995, 6, 1, 0, 59, 21),
 datetime.datetime(1995, 6, 1, 0, 59, 22),
 datetime.datetime(1995, 6, 1, 0, 59, 40)]

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>[datetime.datetime(1995, 6, 1, 0, 57, 12),
 <br>datetime.datetime(1995, 6, 1, 0, 58, 23),
 <br>datetime.datetime(1995, 6, 1, 0, 59, 21),
 <br>datetime.datetime(1995, 6, 1, 0, 59, 22),
 <br>datetime.datetime(1995, 6, 1, 0, 59, 40)]</td>
  </tr>
</table>
    

**Q. Find the difference in time between the first and last log**

In [34]:

def find_difference(start,end):
    
    # Start Code Here

  return end - start



    # End Code Here

In [35]:
difference = find_difference(timestamp_datetime_list[0],timestamp_datetime_list[-1])

print("Difference in minutes is %f" % (difference.total_seconds()//60))

Difference in minutes is 268.000000


<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>Difference in minutes is 268.000000</td>
  </tr>
</table>

**Q. Open a file and save the urls and the timestamp corresponding to it and display first 5 rows**

Format :
    
url timestamp

In [43]:
def save_file(file_name,urls, timestamp_list):
    '''
        Open file in write mode and then check whether length of url list and timestamp list is same.
        If it is then write url  timestamp to the file.
    '''
    # Start Code Here
    with open(file_name, 'w') as f:
      if len(urls) == len(timestamp_list):
        
        for url, time in zip(urls, timestamp_list):
          f.writelines(f"{url} {time}\n")

    

    # End Code Here      

In [44]:
save_file("Filtered timestamp", all_urls, timestamp_list)

In [45]:
show_contents("Filtered timestamp", 5)

GET /~lowey/encyclopedia/help.html 01/Jun/1995:00:57:12

GET /~lowey/encyclopedia/volume_index.html 01/Jun/1995:00:58:23

GET /~scottp/free.html 01/Jun/1995:00:59:21

GET /~scottp/fn1.gif 01/Jun/1995:00:59:22

GET /~lowey/encyclopedia/m/index.html 01/Jun/1995:00:59:40



<table>
  <tr>
  <td>**Expected Output:**<td>
    <td>GET /~lowey/encyclopedia/help.html    01/6/1995:00:57:12

<br>GET /~lowey/encyclopedia/volume_index.html    01/6/1995:00:58:23

<br>GET /~scottp/free.html    01/6/1995:00:59:21

<br>GET /~scottp/fn1.gif    01/6/1995:00:59:22

<br>GET /~lowey/encyclopedia/m/index.html    01/6/1995:00:59:40</td>
  </tr>
</table>
    

**Q. Finally create a function main() which will call all the above functions and print the outputs.**

1. Open the file
2. Show the contents of the file
3. Print all the unique urls
4. Print all the urls
5. Print the frequencies of the urls
6. Parse timestamp to get the timestamps from each record
7. Save the url and the corresponding timestamp to a file
8. Show the contents of the newly created file

In [48]:
import itertools

def main():
    
    file_name = "usask_access_log.txt"
    
    print("The contents of the file are:")
    print()
    show_contents(file_name, 5)
    unique_urls, all_urls = get_urls(file_name)
    print()
    
    print("First five unique urls are:")
    print()
    for i, val in enumerate(itertools.islice(unique_urls, 5)):
        print(val)
    print()
    
    print("First five urls are:")
    print('\n' * 2)
    for i in all_urls[:5]:
        print(i)
    print()    
        
    print("Top five frequent urls are :")
    print()
    freq = frequency(all_urls)
    print(freq[:5])
    print()
    
    timestamp_list, timestamp = parse_timestamp(file_name)

    for i in range(len(timestamp_list)):

        timestamp_list[i] = replace_month(timestamp_list[i])
    
    filtered_file_name = "Filtered timestamp"
    
    print("Saving filtered file")
    print()
    save_file(filtered_file_name, all_urls, timestamp_list)
    print()
    
    print("The contents of the filtered file are:")
    print()
    show_contents(filtered_file_name, 5)
    print()

In [49]:
main()

The contents of the file are:

dialup02.aloha.com - - [01/Jun/1995:00:57:12 -0600] "GET /~lowey/encyclopedia/help.html" 200 2570

dialup02.aloha.com - - [01/Jun/1995:00:58:23 -0600] "GET /~lowey/encyclopedia/volume_index.html" 200 7445

fire.server.net - - [01/Jun/1995:00:59:21 -0600] "GET /~scottp/free.html" 200 5759

fire.server.net - - [01/Jun/1995:00:59:22 -0600] "GET /~scottp/fn1.gif" 200 2164

dialup02.aloha.com - - [01/Jun/1995:00:59:40 -0600] "GET /~lowey/encyclopedia/m/index.html" 200 1898


First five unique urls are:

GET /~lowey/webville/icons/letter_32.gif
GET /~lowey/Saskatchewan/index.html
GET /~lowey/Webville/icons/bus_32.gif
GET /~lowey/webville/icons/sound_32.gif
GET /~lowey/Saskatoon/about_saskatoon/weather.html

First five urls are:



GET /~lowey/encyclopedia/help.html
GET /~lowey/encyclopedia/volume_index.html
GET /~scottp/free.html
GET /~scottp/fn1.gif
GET /~lowey/encyclopedia/m/index.html

Top five frequent urls are :

[('GET /~scottp/free.html', 15), ('GET /~sc

<table>
  <tr>
  <td>**Expected Output:**<td>
    <td style="text-align:left">The contents of the file are:

<br>dialup02.aloha.com - - [01/Jun/1995:00:57:12 -0600] "GET /~lowey/encyclopedia/help.html" 200 2570

<br>dialup02.aloha.com - - [01/Jun/1995:00:58:23 -0600] "GET /~lowey/encyclopedia/volume_index.html" 200 7445

<br>fire.server.net - - [01/Jun/1995:00:59:21 -0600] "GET /~scottp/free.html" 200 5759

<br>fire.server.net - - [01/Jun/1995:00:59:22 -0600] "GET /~scottp/fn1.gif" 200 2164

<br>dialup02.aloha.com - - [01/Jun/1995:00:59:40 -0600] "GET /~lowey/encyclopedia/m/index.html" 200 1898

<br><br>
<br>First five unique urls are:

<br>GET /~macpherc/hibs/hibs.html
<br>GET /~macphed/finite/fe_resources/node36.html
<br>GET /~lowey/encyclopedia/help.html
<br>GET /~macphed/finite/fe_resources/node110.html
<br>GET /~scottp/publish.html
<br>GET /~macpherc/images/new2.gif
<br>GET /~lowey/webville/help/help_directions.html
<br>GET /~macphed/finite/fe_resources/node24.html
<br>GET /~macphed/finite/fe_resources/node91.html
<br>GET /~macphed/finite/fe_resources/node99.html
<br>
<br>First five urls are:

<br>GET /~lowey/encyclopedia/help.html
<br>GET /~lowey/encyclopedia/volume_index.html
<br>GET /~scottp/free.html
<br>GET /~scottp/fn1.gif
<br>GET /~lowey/encyclopedia/m/index.html
<br>
<br>Top five frequent urls are :

<br>[('GET /~scottp/free.html', 15), ('GET /~scottp/publish.html', 7), ('GET /~macphed/finite/fe_resources/fe_resources.html', <br>7), ('GET /~scottp/fn1.gif', 5), ('GET /~macphed/finite/fe_resources/node1.html', 4)]
<br>
<br>Saving filtered file

<br>The contents of the filtered file are:

<br>GET /~lowey/encyclopedia/help.html    01/6/1995:00:57:12

<br>GET /~lowey/encyclopedia/volume_index.html    01/6/1995:00:58:23

<br>GET /~scottp/free.html    01/6/1995:00:59:21

<br>GET /~scottp/fn1.gif    01/6/1995:00:59:22

<br>GET /~lowey/encyclopedia/m/index.html    01/6/1995:00:59:40</td>
  </tr>
</table>
    

# Congratulations

You have completed a small project to analyse a log file.You are likely to reuse this code many a times in your coding career. 
<br> Good understanding of the concepts learnt in this chapter will really help you a lot when you wear the hat of a developer.
<br>Buckle up!
<br>You are doing very well.
<br>See you in the next chapter.